import 'client.dart';

/// Every operation in the OpenAPI document, and the SDK method that wraps it.
///
/// Not used at runtime. The spec-coverage test compares this table against
/// `docs/openapi.json` in both directions and resolves each value to a real
/// method, so an endpoint added to the API fails the build here until it gets
/// a method. The TypeScript SDK carries the same table with the same names.
const Map<String, String> kOperations = {
  'GET /v1/engines': 'engines.list',
  'GET /v1/engines/{engine}/languages': 'engines.languages',
  'GET /v1/engines/{engine}/voices': 'engines.voices',
  'GET /v1/agents': 'agents.list',
  'POST /v1/agents': 'agents.create',
  'GET /v1/agents/{id}': 'agents.retrieve',
  'PATCH /v1/agents/{id}': 'agents.update',
  'DELETE /v1/agents/{id}': 'agents.delete',
  'POST /v1/agents/{id}/test-call': 'agents.testCall',
  'POST /v1/calls': 'calls.create',
  'GET /v1/calls': 'calls.list',
  'GET /v1/calls/{id}': 'calls.retrieve',
  'DELETE /v1/calls/{id}': 'calls.delete',
  'POST /v1/calls/{id}/hangup': 'calls.hangup',
  'GET /v1/calls/{id}/transcript': 'calls.transcript',
  'POST /v1/realtime/sessions': 'realtime.createSession',
  'GET /v1/leads': 'leads.list',
  'POST /v1/leads': 'leads.create',
  'POST /v1/leads/bulk': 'leads.bulkCreate',
  'GET /v1/leads/{id}': 'leads.retrieve',
  'PATCH /v1/leads/{id}': 'leads.update',
  'DELETE /v1/leads/{id}': 'leads.delete',
  'GET /v1/campaigns': 'campaigns.list',
  'POST /v1/campaigns': 'campaigns.create',
  'GET /v1/campaigns/{id}': 'campaigns.retrieve',
  'DELETE /v1/campaigns/{id}': 'campaigns.delete',
  'POST /v1/campaigns/{id}/start': 'campaigns.start',
  'POST /v1/campaigns/{id}/pause': 'campaigns.pause',
  'GET /v1/knowledge-bases': 'knowledgeBases.list',
  'POST /v1/knowledge-bases': 'knowledgeBases.create',
  'GET /v1/knowledge-bases/{id}': 'knowledgeBases.retrieve',
  'PATCH /v1/knowledge-bases/{id}': 'knowledgeBases.update',
  'DELETE /v1/knowledge-bases/{id}': 'knowledgeBases.delete',
  'GET /v1/phone-numbers': 'phoneNumbers.list',
  'POST /v1/phone-numbers': 'phoneNumbers.create',
  'GET /v1/phone-numbers/{id}': 'phoneNumbers.retrieve',
  'PATCH /v1/phone-numbers/{id}': 'phoneNumbers.update',
  'DELETE /v1/phone-numbers/{id}': 'phoneNumbers.delete',
  'GET /v1/sip-trunks': 'sipTrunks.list',
  'POST /v1/sip-trunks': 'sipTrunks.create',
  'GET /v1/sip-trunks/{id}': 'sipTrunks.retrieve',
  'PATCH /v1/sip-trunks/{id}': 'sipTrunks.update',
  'DELETE /v1/sip-trunks/{id}': 'sipTrunks.delete',
  'GET /v1/sip-trunks/{id}/status': 'sipTrunks.status',
  'GET /v1/sip-trunks/{id}/logs': 'sipTrunks.logs',
  'POST /v1/sip-trunks/{id}/test': 'sipTrunks.test',
  'GET /v1/appointments': 'appointments.list',
  'POST /v1/appointments': 'appointments.create',
  'GET /v1/appointments/{id}': 'appointments.retrieve',
  'PATCH /v1/appointments/{id}': 'appointments.update',
  'DELETE /v1/appointments/{id}': 'appointments.delete',
  'GET /v1/usage/events': 'usage.events',
  'GET /v1/usage/summary': 'usage.summary',
  'GET /v1/billing/balance': 'billing.balance',
  'GET /v1/billing/ledger': 'billing.ledger',
  'POST /v1/billing/topups': 'billing.createTopup',
  'GET /v1/webhook': 'webhooks.retrieve',
  'PATCH /v1/webhook': 'webhooks.update',
  'POST /v1/webhook/rotate-secret': 'webhooks.rotateSecret',
  'POST /v1/webhook/test': 'webhooks.test',
  'GET /v1/webhook/deliveries': 'webhooks.deliveries',
  'GET /v1/api-keys': 'apiKeys.list',
  'POST /v1/api-keys': 'apiKeys.create',
  'DELETE /v1/api-keys/{id}': 'apiKeys.revoke',
  'POST /v1/api-keys/{id}/rotate': 'apiKeys.rotate',
};

/// Methods that exist beyond the one-per-operation table.
///
/// Dart cannot hang metadata off an immutable model the way JavaScript can,
/// so the two money paths offer a variant that returns the response as well.
/// They call the same endpoints as their plain counterparts.
const Set<String> kOperationAliases = {
  'calls.createWithResponse',
  'billing.createTopupWithResponse',
};

/// Resolves every table value to the real method on a client.
///
/// Dart has no reflection outside `dart:mirrors`, which does not work on
/// Flutter, so the mapping is written out and the test asserts it covers the
/// table exactly. A method renamed without a change here fails to compile.
Map<String, Function> operationMethods(WixzelVoice client) => {
      'engines.list': client.engines.list,
      'engines.languages': client.engines.languages,
      'engines.voices': client.engines.voices,
      'agents.list': client.agents.list,
      'agents.create': client.agents.create,
      'agents.retrieve': client.agents.retrieve,
      'agents.update': client.agents.update,
      'agents.delete': client.agents.delete,
      'agents.testCall': client.agents.testCall,
      'calls.create': client.calls.create,
      'calls.list': client.calls.list,
      'calls.retrieve': client.calls.retrieve,
      'calls.delete': client.calls.delete,
      'calls.hangup': client.calls.hangup,
      'calls.transcript': client.calls.transcript,
      'realtime.createSession': client.realtime.createSession,
      'leads.list': client.leads.list,
      'leads.create': client.leads.create,
      'leads.bulkCreate': client.leads.bulkCreate,
      'leads.retrieve': client.leads.retrieve,
      'leads.update': client.leads.update,
      'leads.delete': client.leads.delete,
      'campaigns.list': client.campaigns.list,
      'campaigns.create': client.campaigns.create,
      'campaigns.retrieve': client.campaigns.retrieve,
      'campaigns.delete': client.campaigns.delete,
      'campaigns.start': client.campaigns.start,
      'campaigns.pause': client.campaigns.pause,
      'knowledgeBases.list': client.knowledgeBases.list,
      'knowledgeBases.create': client.knowledgeBases.create,
      'knowledgeBases.retrieve': client.knowledgeBases.retrieve,
      'knowledgeBases.update': client.knowledgeBases.update,
      'knowledgeBases.delete': client.knowledgeBases.delete,
      'phoneNumbers.list': client.phoneNumbers.list,
      'phoneNumbers.create': client.phoneNumbers.create,
      'phoneNumbers.retrieve': client.phoneNumbers.retrieve,
      'phoneNumbers.update': client.phoneNumbers.update,
      'phoneNumbers.delete': client.phoneNumbers.delete,
      'sipTrunks.list': client.sipTrunks.list,
      'sipTrunks.create': client.sipTrunks.create,
      'sipTrunks.retrieve': client.sipTrunks.retrieve,
      'sipTrunks.update': client.sipTrunks.update,
      'sipTrunks.delete': client.sipTrunks.delete,
      'sipTrunks.status': client.sipTrunks.status,
      'sipTrunks.logs': client.sipTrunks.logs,
      'sipTrunks.test': client.sipTrunks.test,
      'appointments.list': client.appointments.list,
      'appointments.create': client.appointments.create,
      'appointments.retrieve': client.appointments.retrieve,
      'appointments.update': client.appointments.update,
      'appointments.delete': client.appointments.delete,
      'usage.events': client.usage.events,
      'usage.summary': client.usage.summary,
      'billing.balance': client.billing.balance,
      'billing.ledger': client.billing.ledger,
      'billing.createTopup': client.billing.createTopup,
      'webhooks.retrieve': client.webhooks.retrieve,
      'webhooks.update': client.webhooks.update,
      'webhooks.rotateSecret': client.webhooks.rotateSecret,
      'webhooks.test': client.webhooks.test,
      'webhooks.deliveries': client.webhooks.deliveries,
      'apiKeys.list': client.apiKeys.list,
      'apiKeys.create': client.apiKeys.create,
      'apiKeys.revoke': client.apiKeys.revoke,
      'apiKeys.rotate': client.apiKeys.rotate,
      'calls.createWithResponse': client.calls.createWithResponse,
      'billing.createTopupWithResponse': client.billing.createTopupWithResponse,
    };
